name: Build and push docker image

on: 
  push:
    branches : [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile"
      image_name: ${{ github.repository }}
    # registry_username and registry_api_key must be defined
    secrets: inherit

  deploy:
    needs: [ build-and-push ]
    uses: Eirbware/.github/.github/workflows/deploy-stack.yml@master
    # portainer_stack_webhook must be defined
    secrets: inherit
